src/Entity/QuantiteAjoute.php
<?php

namespace App\Entity;

use App\Repository\QuantiteAjouteRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: QuantiteAjouteRepository::class)]
class QuantiteAjoute
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'quantiteAjoutes')]
    private ?Magasin $magasin = null;

    #[ORM\Column(length: 50,nullable:true)]
    private ?string $quantite_ajoutee = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column(length: 50,nullable:true)]
    private ?string $quantite_sortir = null;

    #[ORM\ManyToOne(inversedBy: 'quantiteAjoutes')]
    private ?Vivre $vivre = null;


    public function __construct()
    {
        $this->created_at = new \DateTimeImmutable();
    }

    
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMagasin(): ?Magasin
    {
        return $this->magasin;
    }

    public function setMagasin(?Magasin $magasin): static
    {
        $this->magasin = $magasin;

        return $this;
    }

    public function getQuantiteAjoutee(): ?string
    {
        return $this->quantite_ajoutee;
    }

    public function setQuantiteAjoutee(string $quantite_ajoutee): static
    {
        $this->quantite_ajoutee = $quantite_ajoutee;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getQuantiteSortir(): ?string
    {
        return $this->quantite_sortir;
    }

    public function setQuantiteSortir(string $quantite_sortir): static
    {
        $this->quantite_sortir = $quantite_sortir;

        return $this;
    }

    public function getVivre(): ?Vivre
    {
        return $this->vivre;
    }

    public function setVivre(?Vivre $vivre): static
    {
        $this->vivre = $vivre;

        return $this;
    }
}

src/Form/QuantiteAjouteType.php
<?php

namespace App\Form;

use App\Entity\QuantiteAjoute;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class QuantiteAjouteType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('quantite_ajoutee')
            ->add('created_at')
            ->add('magasin')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => QuantiteAjoute::class,
        ]);
    }
}

src/Controller/QuantiteAjouteController.php
<?php

namespace App\Controller;

use App\Entity\QuantiteAjoute;
use App\Form\QuantiteAjouteType;
use App\Repository\QuantiteAjouteRepository;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/quantite/ajoute')]
class QuantiteAjouteController extends AbstractController
{
    #[Route('/', name: 'app_quantite_ajoute_index', methods: ['GET'])]
    public function index(QuantiteAjouteRepository $quantiteAjouteRepository): Response
    {
        return $this->render('quantite_ajoute/index.html.twig', [
            'quantite_ajoutes' => $quantiteAjouteRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_quantite_ajoute_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $quantiteAjoute = new QuantiteAjoute();
        $form = $this->createForm(QuantiteAjouteType::class, $quantiteAjoute);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($quantiteAjoute);
            $entityManager->flush();

            return $this->redirectToRoute('app_quantite_ajoute_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('quantite_ajoute/new.html.twig', [
            'quantite_ajoute' => $quantiteAjoute,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_quantite_ajoute_show', methods: ['GET'])]
    public function show(QuantiteAjoute $quantiteAjoute): Response
    {
        return $this->render('quantite_ajoute/show.html.twig', [
            'quantite_ajoute' => $quantiteAjoute,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_quantite_ajoute_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, QuantiteAjoute $quantiteAjoute, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(QuantiteAjouteType::class, $quantiteAjoute);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_quantite_ajoute_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('quantite_ajoute/edit.html.twig', [
            'quantite_ajoute' => $quantiteAjoute,
            'form' => $form,
        ]);
    }

    #[Route('/{id}/delete', name: 'app_quantite_ajoute_delete')]
    public function delete(int $id, QuantiteAjoute $quantiteAjoute, ManagerRegistry $doctrine): Response
    {
        $quantite_ajoute = new QuantiteAjoute();
        $quantite_ajoute = $doctrine->getRepository(QuantiteAjoute::class)->find($id);
   
        if($quantite_ajoute)
        {
            $manager = $doctrine->getManager();
            $manager->remove($quantite_ajoute);
            $manager->flush();
            $this->addFlash("success","Suppression réussi");

        return $this->redirectToRoute('app_quantite_ajoute_index', [], Response::HTTP_SEE_OTHER);
        }
    }
}

templates/quantite_ajoute/_delete_form.html.twig
<form method="post" action="{{ path('app_quantite_ajoute_delete', {'id': quantite_ajoute.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ quantite_ajoute.id) }}">
    <button class="btn">Delete</button>
</form>

templates/quantite_ajoute/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/quantite_ajoute/edit.html.twig
{% extends 'template.html.twig' %}

{% block title %}Edit QuantiteAjoute{% endblock %}

{% block body %}
    <h1>Edit QuantiteAjoute</h1>

    {{ include('quantite_ajoute/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_quantite_ajoute_index') }}">back to list</a>

    {{ include('quantite_ajoute/_delete_form.html.twig') }}
{% endblock %}

templates/quantite_ajoute/index.html.twig
{% extends 'template.html.twig' %}

{% block title %}QuantiteAjoute index{% endblock %}
{% block pagetitle %}Quantité  Ajoutée{% endblock %}
{% block body %}


<div class="container-fluid" >
<div class="card shadow mb-4">
<div class="card-header py-3">
<div class="card-body table-responsive">
<div class="container" >

     <div class="row">
    <table class="table table-bordered table-striped table-highlight">
        <thead>
            <tr>
                <th class="text text-center">Boisson</th>
                <th class="text text-center">Quantite ajoutée</th>
                <th class="text text-center">Quantite sortir</th>
                <th class="text text-center">Date</th>
            </tr>
        </thead>
        <tbody>
        {% for quantite_ajoute in quantite_ajoutes %}
            <tr>
               
                <td class="text text-center">
                {% if quantite_ajoute.magasin.boisson.designation is defined %}
                {{quantite_ajoute.magasin.boisson.designation }}
                {% endif %}
                </td>
                <td class="text text-center">{{ quantite_ajoute.quantiteAjoutee }}</td>
                <td class="text text-center">{{ quantite_ajoute.quantiteSortir }}</td>
                   <!-- 
                   <td class="text text-center">
                        {% if quantite_ajoute.vivre.proteine.nom is defined %}
                        {{quantite_ajoute.vivre.proteine.nom}}
                        {% endif %}
                    </td>
                    !-->
                <td class="text text-center">{{ quantite_ajoute.createdAt ? quantite_ajoute.createdAt|date('d/m/Y') }}</td>

                  <!--  <td>
                    <a href="{{ path('app_quantite_ajoute_edit', {id : quantite_ajoute.id} )}}" class="btn btn-sm btn-outline-success" ><i class="bi bi-pencil text-success ml-5"></i></a>
                    </td>
                    
                    <td><a href="{{ path('app_quantite_ajoute_delete', {id : quantite_ajoute.id} )}}" class="btn btn-sm btn-outline-danger" onclick="return confirm('Etes-vous sûr de vouloir executer cette action')"><i class="bi bi-trash text-danger ml-5"></i></a>
                    </td>
                  !-->


            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

templates/quantite_ajoute/new.html.twig
{% extends 'template.html.twig' %}

{% block title %}New QuantiteAjoute{% endblock %}

{% block body %}
    <h1>Create new QuantiteAjoute</h1>

    {{ include('quantite_ajoute/_form.html.twig') }}

    <a href="{{ path('app_quantite_ajoute_index') }}">back to list</a>
{% endblock %}

templates/quantite_ajoute/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}QuantiteAjoute{% endblock %}

{% block body %}
    <h1>QuantiteAjoute</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ quantite_ajoute.id }}</td>
            </tr>
            <tr>
                <th>Quantite_ajoutee</th>
                <td>{{ quantite_ajoute.quantiteAjoutee }}</td>
            </tr>
            <tr>
                <th>Created_at</th>
                <td>{{ quantite_ajoute.createdAt ? quantite_ajoute.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_quantite_ajoute_index') }}">back to list</a>

    <a href="{{ path('app_quantite_ajoute_edit', {'id': quantite_ajoute.id}) }}">edit</a>

    {{ include('quantite_ajoute/_delete_form.html.twig') }}
{% endblock %}