src/Entity/VenteDrink.php
<?php

namespace App\Entity;

use App\Repository\VenteDrinkRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: VenteDrinkRepository::class)]
class VenteDrink
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'venteDrinks')]
    private ?Boisson $boisson = null;

    #[ORM\Column(length: 50)]
    private ?string $prix_vente = null;

    #[ORM\Column(length: 50)]
    private ?string $quantite_boisson_vendue = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE,options:['default' => 'CURRENT_TIMESTAMP'])]
    private ?\DateTimeInterface $date = null;


    #[ORM\Column(length: 50)]
    private ?string $montant = null;

    

    #[ORM\OneToMany(targetEntity: Recette::class, mappedBy: 'vente_boisson')]
    private Collection $recettes;

    #[ORM\Column(length: 255,nullable:true)]
    private ?string $Statut = null;

    #[ORM\ManyToOne(inversedBy: 'venteDrinks')]
    private ?User $user = null;

    #[ORM\Column(length: 35)]
    private ?string $mode_paiement = null;

    public function __construct()
    {
        $this->date = new \DateTime();
        $this->recettes = new ArrayCollection();
    }

    
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBoisson(): ?Boisson
    {
        return $this->boisson;
    }

    public function setBoisson(?Boisson $boisson): static
    {
        $this->boisson = $boisson;

        return $this;
    }

    public function getPrixVente(): ?string
    {
        return $this->prix_vente;
    }

    public function setPrixVente(string $prix_vente): static
    {
        $this->prix_vente = $prix_vente;

        return $this;
    }

    public function getQuantiteBoissonVendue(): ?string
    {
        return $this->quantite_boisson_vendue;
    }

    public function setQuantiteBoissonVendue(string $quantite_boisson_vendue): static
    {
        $this->quantite_boisson_vendue = $quantite_boisson_vendue;

        return $this;
    }

    public function getMontant(): ?string
    {
        return $this->montant;
    }

    public function setMontant(string $montant): static
    {
        $this->montant = $montant;

        return $this;
    }


    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): static
    {
        $this->date = $date;

        return $this;
    }
    

    /**
     * @return Collection<int, Recette>
     */
    public function getRecettes(): Collection
    {
        return $this->recettes;
    }

    public function addRecette(Recette $recette): static
    {
        if (!$this->recettes->contains($recette)) {
            $this->recettes->add($recette);
            $recette->setVenteBoisson($this);
        }

        return $this;
    }

    public function removeRecette(Recette $recette): static
    {
        if ($this->recettes->removeElement($recette)) {
            // set the owning side to null (unless already changed)
            if ($recette->getVenteBoisson() === $this) {
                $recette->setVenteBoisson(null);
            }
        }

        return $this;
    }


    public function __toString()
    {
    return $this->getBoisson();
    }

    public function getStatut(): ?string
    {
        return $this->Statut;
    }

    public function setStatut(string $Statut): static
    {
        $this->Statut = $Statut;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getModePaiement(): ?string
    {
        return $this->mode_paiement;
    }

    public function setModePaiement(string $mode_paiement): static
    {
        $this->mode_paiement = $mode_paiement;

        return $this;
    }
    
}

src/Entity/VenteRepas.php
<?php

namespace App\Entity;

use App\Repository\VenteRepasRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: VenteRepasRepository::class)]
class VenteRepas
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

   

    #[ORM\Column(length: 50)]
    private ?string $prix_vente_proteine = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE,options:['default' => 'CURRENT_TIMESTAMP'])]
    private ?\DateTimeInterface $date = null;
    
    #[ORM\OneToMany(targetEntity: Recette::class, mappedBy: 'vente_repas')]
    private Collection $recettes;

    #[ORM\ManyToOne(inversedBy: 'venteRepas')]
    private ?Repas $repas = null;

    #[ORM\ManyToOne(inversedBy: 'venteRepas')]
    private ?Proteine $proteine = null;

    #[ORM\Column(length: 255,nullable:true)]
    private ?string $statut = null;

    #[ORM\ManyToOne(inversedBy: 'venteRepas')]
    private ?User $user = null;

    #[ORM\Column(length: 255)]
    private ?string $qte_vendue = null;

    #[ORM\Column(length: 255)]
    private ?string $montant = null;

    #[ORM\Column(length: 50)]
    private ?string $mode_paiement = null;

    #[ORM\Column(length: 50)]
    private ?string $prix_vente_accompagnement = null;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $qte = null;

    

    public function __construct()
    {
        $this->date = new \DateTime();
        $this->recettes = new ArrayCollection();
    }
    
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPrixVenteProteine(): ?string
    {
        return $this->prix_vente_proteine;
    }

    public function setPrixVenteProteine(string $prix_vente_proteine): static
    {
        $this->prix_vente_proteine = $prix_vente_proteine;

        return $this;
    }

    
    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): static
    {
        $this->date = $date;

        return $this;
    }
    

   

    /**
     * @return Collection<int, Recette>
     */
    public function getRecettes(): Collection
    {
        return $this->recettes;
    }

    public function addRecette(Recette $recette): static
    {
        if (!$this->recettes->contains($recette)) {
            $this->recettes->add($recette);
            $recette->setVenteRepas($this);
        }

        return $this;
    }

    public function removeRecette(Recette $recette): static
    {
        if ($this->recettes->removeElement($recette)) {
            // set the owning side to null (unless already changed)
            if ($recette->getVenteRepas() === $this) {
                $recette->setVenteRepas(null);
            }
        }

        return $this;
    }

    public function getRepas(): ?Repas
    {
        return $this->repas;
    }

    public function setRepas(?Repas $repas): static
    {
        $this->repas = $repas;

        return $this;
    }

    public function getProteine(): ?Proteine
    {
        return $this->proteine;
    }

    public function setProteine(?Proteine $proteine): static
    {
        $this->proteine = $proteine;

        return $this;
    }

    public function getStatut(): ?string
    {
        return $this->statut;
    }

    public function setStatut(string $statut): static
    {
        $this->statut = $statut;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getQteVendue(): ?string
    {
        return $this->qte_vendue;
    }

    public function setQteVendue(string $qte_vendue): static
    {
        $this->qte_vendue = $qte_vendue;

        return $this;
    }

    public function getMontant(): ?string
    {
        return $this->montant;
    }

    public function setMmontant(string $montant): static
    {
        $this->montant = $montant;

        return $this;
    }

    public function getModePaiement(): ?string
    {
        return $this->mode_paiement;
    }

    public function setModePaiement(string $mode_paiement): static
    {
        $this->mode_paiement = $mode_paiement;

        return $this;
    }

    public function getPrixVenteAccompagnement(): ?string
    {
        return $this->prix_vente_accompagnement;
    }

    public function setPrixVenteAccompagnement(?string $prix_vente_accompagnement): static
    {
        $this->prix_vente_accompagnement = $prix_vente_accompagnement;

        return $this;
    }

    public function getQte(): ?string
    {
        return $this->qte;
    }

    public function setQte(?string $qte): static
    {
        $this->qte = $qte;

        return $this;
    }

   

    

    
}

src/Form/VenteRepasType.php
<?php

namespace App\Form;

use App\Entity\Calibre;
use App\Entity\CalibreRepas;
use App\Entity\Proteine;
use App\Entity\Repas;
use App\Entity\VenteRepas;
use App\Repository\ProteineRepository;
use App\Repository\CalibreRepository;
use App\Repository\RepasRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\LessThanOrEqual;
use Doctrine\ORM\EntityManagerInterface;




class VenteRepasType extends AbstractType
{

    private $entityManager;

    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
        ->add('repas',EntityType::class,[
            'class'=> Repas::class,
            'label'=> 'Accompagnement',
            'placeholder'=> 'Choisissez un repas',
            'attr'=> ['class'=> 'repas_select'],
            'required' => false,
            'query_builder'=> function(RepasRepository $cr)
            {
                return $cr->createQueryBuilder('r')
                
                ->orderBy('r.accompagnement', 'ASC');
            }
        ])
        ->add('proteine',EntityType::class,[
            'class'=> Proteine::class,
            'placeholder'=> 'Choisissez une protéine',
            'attr'=> ['class'=> 'proteine_select'],
            'required' => false,
            
            'query_builder'=> function(ProteineRepository $cr)
            {
                return $cr->createQueryBuilder('p')
                ->orderBy('p.nom', 'ASC');
            }
        ])
        
        
            ->add('prix_vente_accompagnement',EntityType::class,[
                'label'=> 'Prix de l\'accompagnement',
                'class'=> CalibreRepas::class,
                'choice_label'=> 'prix',
                 'placeholder'=> 'Choisir le prix',
                 'attr'=> ['class'=> 'accompagnement_select'],
                 'required'=> false,
                 'choices'=> [],
                 'mapped'=> true,

            ])

            ->add('prix_vente_proteine',EntityType::class,[
                'label'=> 'Prix de la proteine',
                'class'=> Calibre::class,
                'choice_label' => 'masse',
                 'placeholder'=> 'Choisir le prix',
                 'attr'=> ['class'=> 'calibre_select'],
                 'required'=> false,
                // 'disabled'=> true,
                'choices'=> [],
                'mapped'=> true,
                ])


            
            ->add('qte_vendue',NumberType::class,[
                'label'=> 'Quantité vendue Proteine',
                'invalid_message' => 'Saisissez des chiffers uniquement',
                'required' => false,
                'attr' => array(
                    'style' => 'display: none',
                    'class'=> 'proteine'
                ),
                
            ])
            ->add('qte',NumberType::class,[
                'label'=> 'Quantité vendue Accompagnement',
                'invalid_message' => 'Saisissez des chiffers uniquement',
                'required' => false,
                'attr' => array(
                    'style' => 'display: none',
                    'class'=> 'repas'
                ),
            ])
            ->add('date',DateType::class,[
                'widget' => 'single_text',
                'label'=> 'Date',
                'input'=> 'datetime',
                'constraints' => [
                    new LessThanOrEqual('today'),
                    
                ], 
                 
            ])
            ->add('mode_paiement',ChoiceType::class,[
                'label'=> 'Mode de paiement',
                'placeholder'=> 'Choisissez un mode de paiement',
                'choices'=>[
                    'Paiement Numéraire'=> 'Paiement Numéraire',
                    'Paiement Electronique'=> 'Paiement Electronique',
                ],
            ])
            ->add('VALIDER',SubmitType::class)

            
        ;



// Ajoutez un événement pour mettre à jour les communes en fonction du département sélectionné
$builder->addEventListener(FormEvents::PRE_SUBMIT, function (FormEvent $event) {
    $form = $event->getForm();
    $data = $event->getData();

if (isset($data['proteine'])) {
    $proteineId = $data['proteine'];

    // Chargez les calibres pour la protéine  sélectionnée
    $calibres = $this->entityManager->getRepository(Calibre::class)->findBy(['proteine' => $proteineId]);

    $form->add('prix_vente_proteine',EntityType::class,[
            'label'=> 'Prix de la proteine',
            'class'=> Calibre::class,
            'choice_label' => 'masse',
             'placeholder'=> 'Choisir le prix',
             'attr'=> ['class'=> 'calibre_select'],
             'required'=> false,
            // 'disabled'=> true,
            'choices'=> $calibres,
            'mapped'=> true,
            ]);
        }
    });



// Ajoutez un événement pour mettre à jour les communes en fonction du département sélectionné
$builder->addEventListener(FormEvents::PRE_SUBMIT, function (FormEvent $event) {
    $form = $event->getForm();
    $data = $event->getData();

if (isset($data['repas'])) {
    $repasId = $data['repas'];

    // Chargez les calibres pour la protéine  sélectionnée
    $calibre_repas = $this->entityManager->getRepository(CalibreRepas::class)->findBy(['repas' => $repasId]);

    $form->add('prix_vente_accompagnement',EntityType::class,[
        'label'=> 'Prix de l\'accompagnement',
        'class'=> CalibreRepas::class,
        'choice_label'=> 'prix',
         'placeholder'=> 'Choisir le prix',
         'attr'=> ['class'=> 'accompagnement_select'],
         'required'=> false,
         'choices'=> $calibre_repas,
         'mapped'=> true,
          
            ]);
        }
    });



    





        
    }



    







    
    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => VenteRepas::class,
        ]);
    }
}

templates/vente_repas/_delete_form.html.twig
<form method="post" action="{{ path('app_vente_repas_delete', {'id': vente_repa.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ vente_repa.id) }}">
    <button class="btn">Delete</button>
</form>

templates/vente_repas/_form.html.twig
<section class="section">
      <div class="row">
        <div class="col-lg-12">

          <div class="card">
            <div class="card-body">
              <h5 class="card-title"></h5>


{{ form_start(form) }}
<div class="row">

<div class="col-6">{{ form_row(form.repas) }}</div>
<div class="col-6">{{ form_row(form.proteine) }}</div>

</div>

<div class="row">
<div class="col-6">{{ form_row(form.qte) }}</div>
<div class="col-6">{{ form_row(form.qte_vendue) }}</div>


</div>

<div class="row">
<div class="col-6">{{ form_row(form.prix_vente_accompagnement) }}</div>
<div class="col-6">{{ form_row(form.prix_vente_proteine) }}</div>
</div>

<div class="row">
<div class="col-6">{{ form_row(form.mode_paiement) }}</div>
<div class="col-6">{{ form_row(form.date) }}</div>
</div>


{{ form_end(form) }}

<script>

  document.addEventListener('DOMContentLoaded', function() {
    document.querySelector('.repas_select').addEventListener('change', function() {
        const qte = document.querySelector('.repas');
        if (this.value !== '') {
            qte.style.display = 'block';
        } else {
            qte.style.display = 'none';
        }
    });
});

  document.addEventListener('DOMContentLoaded', function() {
    document.querySelector('.proteine_select').addEventListener('change', function() {
        const inputForArticle = document.querySelector('.proteine');
        
        if (this.value !== '') {
            inputForArticle.style.display = 'block';
        } else {
            inputForArticle.style.display = 'none';
        }
    });
});


//document.addEventListener('DOMContentLoaded', function() {
//  document.querySelector('.proteine_select').addEventListener('change', function() {
//      const proteine_calibre = document.querySelector('.calibre_select');
//      if (this.value !== '') {
//        proteine_calibre.disabled = false;
//      } else {
//        proteine_calibre.disabled = true;
//      }
//  });
//});



 // Votre script JavaScript ici
 $(document).ready(function() {
  $('.proteine_select').change(function() {
      var selectedProteine = $(this).val();
      if (selectedProteine) {
          $('.calibre_select').prop('disabled', false);
      } else {
          $('.calibre_select').prop('disabled', true);
      }
  });
});


 // Votre script JavaScript ici
 $(document).ready(function() {
  $('.repas_select').change(function() {
      var selectedProteine = $(this).val();
      if (selectedProteine) {
          $('.accompagnement_select').prop('disabled', false);
      } else {
          $('.accompagnement_select').prop('disabled', true);
      }
  });
});



</script>

templates/vente_repas/cart_index.html.twig
{% extends 'template.html.twig' %}

{% block title %}Panier{% endblock %}


{% block body %}

    <main class="container">
        <section class="row">
            <div class="col-sm-6">
                <h1>Panier</h1>
                <table class="table">
                    <thead>
                        <tr>
                            <th>Plat</th>
                            
                            <th>Quantité</th>
                            
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for element in data %}
                        
                            <tr>
                                <td>{{ element.repas.accompagnement }}</td>
                                    
                                
                                    
                                
                                <td>{{ element.qte_vendue }} €</td>
                                <td>
                                <a href="{{ path('cart_add', {id: element.repas.id}) }}" class="btn btn-success"><i class="fa fa-plus"></i></a>
                                <a href="" class="btn btn-warning"><i class="fa-solid fa-window-minimize"></i></a>
                                <a href="" class="btn btn-danger"><i class="fa fa-trash"></i></a>
                               </td>
                            </tr>
                        {% else %}
                            <tr>
                                <td colspan="5">Votre panier est vide</td>
                            </tr>
                            
                        {% endfor %}
                    </tbody>
                    <tfoot>
                        <tr>
                            <td colspan="3">Total :</td>
                            <td></td>
                            <td>
                            <a href="{{ path('empty') }}" class="btn btn-danger">Vider</a>
                            </td>
                        </tr>
                    </tfoot>
                </table>
                <a href="" class="btn btn-primary">Valider mon Panier</a>
            <a href="{{ path('app_vente_repas_new') }}" class="btn btn-success">Continuer la commande</a>
            </div>


        </section>
    </main>



  

{% endblock %}

templates/vente_repas/edit.html.twig
{% extends 'template.html.twig' %}

{% block title %}Edit VenteRepas{% endblock %}

{% block body %}
    <h1>Edit VenteRepas</h1>

    {{ include('vente_repas/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_vente_repas_index') }}">back to list</a>

{% endblock %}

templates/vente_repas/historique.html.twig
{% extends 'template.html.twig' %}

{% block title %}VenteDrink index{% endblock %}

{% block pagetitle %}Historiques des ventes annuler{% endblock %}
{% block body %}

<div class="container-fluid" >
<div class="card shadow mb-4">
    <div class="card-header py-3">
<div class="card-body table-responsive">
<div class="container" >

     <div class="row">
    <table class="table table-bordered table-striped table-highlight">

        <thead>
            <tr>
                <th>Accompagnement</th>
                <th>Protéines</th>
                <th>Prix de vente</th>
                <th>Quantité vendue</th>
                <th>Montant</th>
                <th>Auteur</th>
                <th>Date de la vente</th>
                 
            </tr>
        </thead>
        <tbody>
            {% for cat in cats.getRepasAnnuler() %}
            <tr>
            <td>{{cat.accompagnement}}</td>
                <td>{{cat.name}}</td>
                <td>{{cat.prixVenteProteine}}</td>
                <td>{{cat.prixVenteAccompagnement}}</td>
                <td>{{cat.montant}}</td>
                <td>{{cat.nom}}</td>
                <td>{{cat.date|date('d-m-Y')}}</td>
          </td>
           </tr>
       
        {% endfor %}
        </tbody>
    </table>

    
    


{% endblock %}

templates/vente_repas/index.html.twig
{% extends 'template.html.twig' %}

{% block title %}VenteRepas index{% endblock %}

{% block body %}

{% for flash_error in app.flashes('error') %}
<div class="alert alert-danger" role="alert">{{ flash_error }}</div>
{% endfor %}

<style>
.disabled{
  pointer-events: none;
}
</style>

        <div class="container-fluid" >
        <div class="card shadow mb-4">
        <div class="card-header py-3">
        <div class="card-body table-responsive">
        <div class="container" >

      <div class="row">
      <table class="table table-bordered table-striped table-highlight">
      <a href="{{path('app_vente_repas_new')}}" class="btn btn-success mb-3">Nouvelle vente<i class="bi bi-plus"></i></a>
        <thead>
            <tr>
                
                <th>Accompagnement</th>
                <th>Quantité Accompagnement</th>
                <th>Prix Accompagnement</th>
                <th>Protéine</th>
                <th>Quantité Proteine</th>
                <th>Prix Proteine</th>
                <th>montant</th>
                <th>Mode de paiement</th>
                {% if is_granted('ROLE_ADMIN')%}
                <th>Auteur</th>
                {% endif %}
                <th>Date</th>
                <th>Statut</th>
                {% if is_granted('ROLE_ADMIN')%}
                <th>action 1</th>
                <th>action 2</th>
                {% endif %}
                <th>action</th>  
            </tr>
        </thead>
        <tbody>
        {% for vente_repa in vente_repas %}
            <tr>
                
                <td>
                    {% if vente_repa.repas.accompagnement is defined %}
                    {{vente_repa.repas.accompagnement }}
                    {% endif %}
                </td>
            <td>{{ vente_repa.qte }}</td>
            <td>{{ vente_repa.prixVenteAccompagnement}}</td>

                <td>
                    {% if vente_repa.proteine.nom is defined %}
                    {{vente_repa.proteine.nom }}
                    {% endif %}
                </td>
                <td>{{ vente_repa.qteVendue }}</td>
                <td>{{ vente_repa.prixVenteProteine}}</td>
                
                <td>{{ vente_repa.montant }}</td>
                <td>{{ vente_repa.modepaiement}}</td>
                {% if is_granted('ROLE_ADMIN')%}
                <td>{{ vente_repa.user.nom }}</td>
                {% endif %}
                <td>{{ vente_repa.date|date('d-m-Y') }}</td>
                <td>{{ vente_repa.statut}}</td>
                {% if is_granted('ROLE_ADMIN')%}
                <td>
                <a href="{{ path('app_vente_repas_edit', {id : vente_repa.id} )}}" class="btn btn-sm btn-outline-success" >Modifier</a>
                </td>
                <td>
                <a href="{{ path('app_vente_repas_delete', {id : vente_repa.id} )}}" class="btn btn-sm btn-outline-danger" onclick="return confirm('Etes-vous sûr de vouloir exécuter cette action')">Supprimer</a>
                </td>
            {% endif %}
            <td>
                {% if vente_repa.statut == 'annuler' %} 
               <a href="{{ path('app_vente_repas_annuler', {id : vente_repa.id} )}}" class="btn btn-sm btn-outline-primary disabled" >ANNULER</a>
               {% else %}
               <a href="{{ path('app_vente_repas_annuler', {id : vente_repa.id} )}}" class="btn btn-sm btn-outline-primary">ANNULER</a>
               {% endif %}
            </td>
            </tr>
          {% else %}
            <tr>
                <td colspan="12">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/vente_repas/new.html.twig
{% extends 'template.html.twig' %}

{% block title %}New VenteRepas{% endblock %}
{% block pagetitle %}Ajouter une nouvelle vente{% endblock %}
{% block body %}
    

    {{ include('vente_repas/_form.html.twig') }}

    <a href="{{ path('app_vente_repas_index') }}">back to list</a>

   

{% endblock %}


{% block javascripts %} 
{{ parent() }}
    <script>
        $(function () {        
            //$('.select2').select2();

            //alert('bonjour');

            $('.proteine_select').bind('change', function(){
                var id_proteine = $(this).val();


                
                $.ajax({
                    url: '{{ path('select_calibre_async') }}',
                    type: "POST",
                    dataType: "json",
                        data: {
                            "id_proteine": id_proteine                 
                                                  
                        },
                        async: true,
                        error: function (error) {
                            //console.log(error)
                            var error_message = '';
                            if(error.status == 404){
                                error_message = error.responseJSON;
                            }
                            else{
                                error_message = "Ooouups ! Une erreur est survenue !";
                            }

                          
                        },

                       
                        success: function (html_data, status) {
                            //console.log(status)
                            
                            // refresh the domaine select options
                         //   $('.calibre_select').prop('disabled', false);
                            $('.calibre_select').html(html_data);

                            // close the modal
                           
                        }
                })
            });



            
            $('.repas_select').bind('change', function(){
                var id_repas = $(this).val();


                
                $.ajax({
                    url: '{{ path('select_calibre_repas_async') }}',
                    type: "POST",
                    dataType: "json",
                        data: {
                            "id_repas": id_repas                 
                                                  
                        },
                        async: true,
                        error: function (error) {
                            //console.log(error)
                            var error_message = '';
                            if(error.status == 404){
                                error_message = error.responseJSON;
                            }
                            else{
                                error_message = "Ooouups ! Une erreur est survenue !";
                            }

                          
                        },
                        success: function (html_data, status) {
                            //console.log(status)
                            
                            // refresh the domaine select options
                            $('.accompagnement_select').html(html_data);

                            // close the modal
                           
                        }
                })
            });


       








        });



 
















        
    </script>
{% endblock %}


                      

templates/vente_repas/show.html.twig
{% extends 'template.html.twig' %}

{% block title %}VenteRepas{% endblock %}

{% block body %}
    <h1>VenteRepas</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ vente_repa.id }}</td>
            </tr>
            <tr>
                <th>Designation</th>
                <td>{{ vente_repa.designation }}</td>
            </tr>
            <tr>
                <th>Quantite_vendue</th>
                <td>{{ vente_repa.quantiteVendue }}</td>
            </tr>
            <tr>
                <th>Prix_vente</th>
                <td>{{ vente_repa.prixVente }}</td>
            </tr>
            <tr>
                <th>Montant</th>
                <td>{{ vente_repa.montant }}</td>
            </tr>
            <tr>
                <th>Created_at</th>
                <td>{{ vente_repa.createdAt ? vente_repa.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_vente_repas_index') }}">back to list</a>

    <a href="{{ path('app_vente_repas_edit', {'id': vente_repa.id}) }}">edit</a>

    {{ include('vente_repas/_delete_form.html.twig') }}
{% endblock %}