src/Entity/DepenseAppro.php
<?php

namespace App\Entity;

use App\Repository\DepenseApproRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: DepenseApproRepository::class)]
class DepenseAppro
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'depenseAppros')]
    private ?Boisson $boisson = null;

    #[ORM\Column(length: 50)]
    private ?string $quantite_achete = null;

    #[ORM\Column(length: 50)]
    private ?string $prix_unitaire = null;

    #[ORM\Column(length: 50)]
    private ?string $montant = null;


    #[ORM\Column(type: Types::DATETIME_MUTABLE,options:['default' => 'CURRENT_TIMESTAMP'])]
    private ?\DateTimeInterface $date = null;

    #[ORM\Column(length: 30)]
    private ?string $nombre_trou = null;

    #[ORM\ManyToOne(inversedBy: 'depenseAppros')]
    private ?User $user = null;

   
    public function __construct()
    {
        $this->date = new \DateTime();
    }
    
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBoisson(): ?Boisson
    {
        return $this->boisson;
    }

    public function setBoisson(?Boisson $boisson): static
    {
        $this->boisson = $boisson;

        return $this;
    }

    public function getQuantiteAchete(): ?string
    {
        return $this->quantite_achete;
    }

    public function setQuantiteAchete(string $quantite_achete): static
    {
        $this->quantite_achete = $quantite_achete;

        return $this;
    }

    public function getPrixUnitaire(): ?string
    {
        return $this->prix_unitaire;
    }

    public function setPrixUnitaire(string $prix_unitaire): static
    {
        $this->prix_unitaire = $prix_unitaire;

        return $this;
    }

    public function getMontant(): ?string
    {
        return $this->montant;
    }

    public function setMontant(string $montant): static
    {
        $this->montant = $montant;

        return $this;
    }

   

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): static
    {
        $this->date = $date;

        return $this;
    }

    public function getNombreTrou(): ?string
    {
        return $this->nombre_trou;
    }

    public function setNombreTrou(string $nombre_trou): static
    {
        $this->nombre_trou = $nombre_trou;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

   
}

src/Form/DepenseApproType.php
<?php

namespace App\Form;

use App\Entity\Boisson;
use App\Entity\DepenseAppro;
use App\Repository\BoissonRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\LessThanOrEqual;

class DepenseApproType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('quantite_achete',NumberType::class,[
                'invalid_message' => 'Saisissez des chiffers uniquement',
            ])
            ->add('prix_unitaire',NumberType::class,[
                'invalid_message' => 'Saisissez des chiffers uniquement',
            ])
            ->add('date',DateType::class,[
                'widget' => 'single_text',
                'label'=> 'Date',
                'constraints' => [
                    new LessThanOrEqual('today'),
                    
                ],
            ])
            ->add('nombre_trou',NumberType::class,[
                'invalid_message' => 'Saisissez des chiffers uniquement',
            ])
            ->add('boisson',EntityType::class,[
                'class'=> Boisson::class,
                'placeholder'=> 'Choisissez une boisson',
                
                'query_builder'=> function(BoissonRepository $cr)
                {
                    return $cr->createQueryBuilder('B')
                    
                    ->orderBy('B.designation', 'ASC');
                }
            ])
            ->add('valider',SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => DepenseAppro::class,
        ]);
    }
}

src/Controller/DepenseApproController.php
<?php

namespace App\Controller;

use App\Entity\DepenseAppro;
use App\Entity\User;
use App\Form\DepenseApproType;
use App\Repository\DepenseApproRepository;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/depense/appro')]
class DepenseApproController extends AbstractController
{
    #[Route('/', name: 'app_depense_appro_index', methods: ['GET'])]
    public function index(DepenseApproRepository $depenseApproRepository): Response
    {
       // $depense = $depenseApproRepository->getNb();
        
        return $this->render('depense_appro/index.html.twig', [
            'depense_appros' => $depenseApproRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_depense_appro_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        
        $id = $this->getUser();
        $depenseAppro = new DepenseAppro();
        $form = $this->createForm(DepenseApproType::class, $depenseAppro);
        $form->handleRequest($request);
        $total = 0;
        if ($form->isSubmitted() && $form->isValid()) {
            $quantite = $form->getData()->getQuantiteAchete();
            $prix = $form->getData()->getPrixUnitaire();
            $nombre_trou = $form->getData()->getNombreTrou();
            $montant = (int)$quantite * (int)$prix;
            $trou = (int)$quantite * (int)$nombre_trou;
            $depenseAppro->setMontant($montant);
            $depenseAppro->setNombreTrou($trou);
            $depenseAppro->setUser($id);
            $entityManager->persist($depenseAppro);
            $entityManager->flush();

            return $this->redirectToRoute('app_depense_appro_index', [], Response::HTTP_SEE_OTHER);
        }
         
        return $this->renderForm('depense_appro/new.html.twig', [
            'depense_appro' => $depenseAppro,
            'form' => $form,
            'total' => $total,
        ]);
    }

    #[Route('/{id}', name: 'app_depense_appro_show', methods: ['GET'])]
    public function show(DepenseAppro $depenseAppro): Response
    {
        return $this->render('depense_appro/show.html.twig', [
            'depense_appro' => $depenseAppro,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_depense_appro_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, DepenseAppro $depenseAppro, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(DepenseApproType::class, $depenseAppro);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $quantite = $form->getData()->getQuantiteAchete();
            $prix = $form->getData()->getPrixUnitaire();
            $montant = $quantite * $prix;
           
            $depenseAppro->setMontant($montant);
            $entityManager->persist($depenseAppro);
            $entityManager->flush();

            return $this->redirectToRoute('app_depense_appro_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('depense_appro/edit.html.twig', [
            'depense_appro' => $depenseAppro,
            'form' => $form,
        ]);
    }

    #[Route('/{id}/delete', name: 'app_depense_appro_delete')]
    public function delete(Request $request, ManagerRegistry $doctrine, int $id): Response
    {
        $depense = new DepenseAppro();
        $depense = $doctrine->getRepository(DepenseAppro::class)->find($id);
   
        if($depense)
        {
            $manager = $doctrine->getManager();
            $manager->remove($depense);
            $manager->flush();
            $this->addFlash("success","Suppression réussi");

            return $this->redirectToRoute('app_depense_appro_index', [], Response::HTTP_SEE_OTHER);
        }

    }
}

templates/depense_appro/_delete_form.html.twig
<form method="post" action="{{ path('app_depense_appro_delete', {'id': depense_appro.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ depense_appro.id) }}">
    <button class="btn">Delete</button>
</form>

templates/depense_appro/_form.html.twig
<section class="section">
      <div class="row">
        <div class="col-lg-12">

          <div class="card">
            <div class="card-body">
              <h5 class="card-title"></h5>
{{ form_start(form) }}
<div class="row">
<div class="col-12">{{ form_row(form.boisson) }}</div>
</div>

<div class="row">
<div class="col-6">{{ form_row(form.nombre_trou,{'label' : 'Nombre de trou casier'}) }}</div>
<div class="col-6"> {{ form_row(form.prix_unitaire, { 'label' : 'Prix Unitaire Casier' }) }} </div>
</div>

<div class="row">

<div class="col-6">{{ form_row(form.quantite_achete,{'label' : 'Nombre de casier acheté'}) }}</div>
<div class="col-6">{{ form_row(form.date) }}</div>

</div>
{{ form_end(form) }}

templates/depense_appro/edit.html.twig
{% extends 'template.html.twig' %}

{% block title %}Edit DepenseAppro{% endblock %}

{% block body %}
    <h1>Edit DepenseAppro</h1>

    {{ include('depense_appro/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_depense_appro_index') }}">back to list</a>

    
{% endblock %}

templates/depense_appro/index.html.twig
{% extends 'template.html.twig' %}

{% block title %}DepenseAppro index{% endblock %}

{% block body %}

<div class="container-fluid" >
<div class="card shadow mb-4">
<div class="card-header py-3">
<div class="card-body table-responsive">
<div class="container" >

     <div class="row">
    <table class="table table-bordered table-striped table-highlight"> 
    <a href="{{ path('app_depense_appro_new') }}" class="btn btn-success mb-3">Nouvelle dépense<i class="bi bi-plus"></i></a>

    
        <thead>
            <tr>
                <th>Boisson</th>
                <th>Quantité achetée</th>
                <th>Prix unitaire</th>
                <th>Montant</th>
                <th>Nombre de bouteilles</th>
                <th>Date</th>
                <th>action1</th>
                <th>action2</th>
            </tr>
        </thead>
        <tbody>
        {% for depense_appro in depense_appros %}
            <tr>
                <td>{{ depense_appro.boisson.designation }}</td>
                <td>{{ depense_appro.quantiteAchete }}</td>
                <td>{{ depense_appro.prixUnitaire }}</td>
                <td>{{ depense_appro.montant }}</td>
                <td> {{ depense_appro.NombreTrou }}  </td>
                <td>{{ depense_appro.date ? depense_appro.date|date('d-m-Y') }}</td>
                <td>
                    <a href="{{ path('app_depense_appro_edit', {'id': depense_appro.id}) }}" class="btn btn-sm btn-outline-success"><i class="bi bi-pencil text-success ml-5"></i></a>
                </td>
                {% if is_granted('ROLE_ADMIN')%}
            <td>
            <a href="{{ path('app_depense_appro_delete', {id : depense_appro.id} )}}" class="btn btn-sm btn-outline-danger" onclick="return confirm('Etes-vous sûr de vouloir supprimer La Boisson: '+ {{depense_appro.id}})"><i class="bi bi-trash text-danger ml-5"></i></a>
            </td>
            {% endif %}
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    
{% endblock %}

templates/depense_appro/new.html.twig
{% extends 'template.html.twig' %}

{% block title %}New dépense{% endblock %}
{% block pagetitle %}Create new Depense{% endblock %}
{% block body %}
    

    {{ include('depense_appro/_form.html.twig') }}

    <a href="{{ path('app_depense_appro_index') }}">back to list</a>
{% endblock %}

templates/depense_appro/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}DepenseAppro{% endblock %}

{% block body %}
    <h1>DepenseAppro</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ depense_appro.id }}</td>
            </tr>
            <tr>
                <th>Quantite_achete</th>
                <td>{{ depense_appro.quantiteAchete }}</td>
            </tr>
            <tr>
                <th>Prix_unitaire</th>
                <td>{{ depense_appro.prixUnitaire }}</td>
            </tr>
            <tr>
                <th>Montant</th>
                <td>{{ depense_appro.montant }}</td>
            </tr>
            <tr>
                <th>Total_depense</th>
                <td>{{ depense_appro.totalDepense }}</td>
            </tr>
            <tr>
                <th>Created_at</th>
                <td>{{ depense_appro.createdAt ? depense_appro.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_depense_appro_index') }}">back to list</a>

    <a href="{{ path('app_depense_appro_edit', {'id': depense_appro.id}) }}">edit</a>

    {{ include('depense_appro/_delete_form.html.twig') }}
{% endblock %}